tegra-state-scripts: remove the correct file
When updating the nv_boot_control.conf file during the payload update the wrong file was removed. The "${mnt}/etc/nv_boot_control.conf" file is a symbolic link to "${mnt}/var/lib/nvbootctrl/nv_boot_control.conf". When the symbolic link in /etc is removed, the next firmware update will fail.

Instead of removing the symbolic link, the file it points to is removed and recreated after the setup-nv-boot-control script is executed.

Signed-off-by: Boris Nagels <develop@focusware.nl>

diff --git a/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script-uboot b/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script-uboot
--- a/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script-uboot
+++ b/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script-uboot
@@ -47,9 +47,11 @@ mount --bind /dev "${mnt}/dev"
 # TNSPEC in the update payload. But first we have to set up the
 # configuration file with the TNSPEC.
 if [ -L "${mnt}/etc/nv_boot_control.conf" -a -x "${mnt}/usr/bin/setup-nv-boot-control" ]; then
-    rm "${mnt}/etc/nv_boot_control.conf"
+    if [ -f "${mnt}/var/lib/nvbootctrl/nv_boot_control.conf" ]; then
+        rm "${mnt}/var/lib/nvbootctrl/nv_boot_control.conf"
+    fi
     if ! chroot "${mnt}" /usr/bin/setup-nv-boot-control; then
-	echo "ERR: could not initialize nv_boot_control.conf in new rootfs" >&2
+        echo "ERR: could not initialize nv_boot_control.conf in new rootfs" >&2
     fi
 fi
 if ! chroot "${mnt}" /usr/sbin/nv_update_engine --install no-reboot; then
